---
- name: update apt and packages
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    upgrade: dist
- name: Set firefox and Nautilus as only favourites
  command: /usr/bin/gsettings set org.gnome.shell favorite-apps "['firefox.desktop','org.gnome.Nautilus.desktop','org.gnome.gedit.desktop','org.gnome.Terminal.desktop']"
- name: Configure gedit
  command: "{{item}}"
  with_items:
    - /usr/bin/gsettings set org.gnome.gedit.preferences.editor display-line-numbers "true"
    - /usr/bin/gsettings set org.gnome.gedit.preferences.editor highlight-current-line "true"
    - /usr/bin/gsettings set org.gnome.gedit.preferences.editor insert-spaces "true"
    - /usr/bin/gsettings set org.gnome.gedit.preferences.editor tabs-size "uint32 4"
    - /usr/bin/gsettings set org.gnome.gedit.preferences.editor bracket-matching "true"
- name: Copy .bashrc.d
  copy:
    src: .bashrc.d
    dest: "{{ ansible_env.HOME }}" 
- name: Make .rc files in .bashrc.d executable
  file:
    dest: "{{ ansible_env.HOME }}/.bashrc.d"
    mode: '0750'
    recurse: yes
- name: Configure bashrc
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    insertafter: EOF
    block: |
        # include all files from .bashrc.d/
        if [ -d "$HOME/.bashrc.d" ]; then
            for rc in "$HOME/.bashrc.d/"*; do
                if [ -f "$rc" ]; then
                    . "$rc"
                fi
            done
        fi
    backup: yes
