---
- name: Test the connection and sudo abilities
  hosts: all
  remote_user: "{{ rem_ssh_user }}"
  become: yes
  become_method: sudo
  tasks:
    - name: create file 'ansible.tst' in '/root/'
      copy:
        content: ansible-test
        dest: /root/ansible.tst
